### ISSUE TITLE
Subtracting a tiny bit of motion compensation for immersion

### ISSUE THREAD

**Issue by keem85** [openvrmc/OpenVR-MotionCompensation#14]
Not an issue. Just a request to make a tiny bit of headroom for motion. Say 80% motion compensation instead of 100%, leaving a little bit of visual cues inside the car that gives us the feeling of acceleration and braking. That would probably also leave a little headroom for "head bobbing" without being glued 100% to the car seat.

**Comment by rosskevin** [comment]
Please discuss on #development of https://discord.gg/r7krmSd if not an issue.
