### ISSUE TITLE
Windows 10 2004 (the last update) potential problems

### ISSUE THREAD

**Issue by SeriouSerg** [openvrmc/OpenVR-MotionCompensation#16]
Hi!
Can anyone confirm or deny issues with the latest Windows 10 update 2004 in this fork?
https://github.com/matzman666/OpenVR-InputEmulator/issues/189

**Comment by TaidaDave** [comment]
Well they existed and people had to roll back to 1909 build of Windows 10, surprisingly many people didn't experience any problems, and people who did had gtx 1070ti /1080ti

**Comment by rosskevin** [comment]
Any thoughts on this @Dschadu?  Is this a software bug or an upstream (windows/openvr) bug?  

If upstream, we should close and add to the readme.

**Comment by Dschadu** [comment]
I'm still on 1903, so no way to test it on my end. Lets wait on some more user input.

**Comment by SeriouSerg** [comment]
I tested the original OpenVR-Input Emulator and can confirm that it was completely broken by Win 10 2004. There is no info about this fork, I rolled back to 1903.

**Comment by apointner** [comment]
I can confirm this, OpenVR-MotionCompensation_0_3_2 is not running after new Windows Update. 
I did a clean install but no cogwheel is showing up in VR.
Also the old OpenVR Input Emulator doas not work anymore.

**Comment by Dschadu** [comment]
Issue seems to be resolved
