### ISSUE TITLE
Compensating for CoR

### ISSUE THREAD

**Issue by kennardconsulting** [openvrmc/OpenVR-MotionCompensation#21]
Hi there,

OVRMC is amazing! Thanks so much for your work on it.

As I understand (still a newbie, sorry), with non-lighthouse tracking systems you have to mount the controller in front of you (so the HMD can see it) not directly behind your head. This is not ideal because the Centre of Rotation (CoR) of the controller is now different from the CoR of the motion simulator.

Is it possible (or necessary?) to add a feature to OVRMC where you can 'teach' it what this offset is? So that the CoR of the controller matches the CoR of the motion simulator?

**Comment by Dschadu** [comment]
Hey, the offset is already calculated automatically. No need to enter it. You can mount the controller anywhere on your simulator!
