### ISSUE TITLE
Reduce amount of smoothing for tracker position

### ISSUE THREAD

**Issue by phutflesz** [openvrmc/OpenVR-MotionCompensation#22]
As the title says, is it possible to reduce the amount of smoothing (and thus delay) that is applied to the tracker position, more like the original OpenVR-InputEmulator? Even if it means more jaggy movement since I guess this involves removing a filter that was intentionally implemented.

**Comment by Dschadu** [comment]
You need to adjust the filter values. Try LPF Beta value of 0.8 and DEMA samples of 6.
Check https://ovrmc.dschadu.de/en/howtouse#lpf-beta-value for more information!

**Comment by phutflesz** [comment]
Ok thanks, and is it also possible to switch the axis mapping of a tracker? I sometimes have the issue that forward/backward movement of the tracker results in upward/downward compensation instead, adding to the movement instead of compensating for it.
Every Steam VR update I get has the chance of causing this issue and I can only hope that the next one will fix it again, until the one after maybe breaks it again. I'm using Vive controllers as trackers. Thanks a lot in advance!
