### ISSUE TITLE
Transducer interference with reference tracking - research

### ISSUE THREAD

**Issue by rosskevin** [openvrmc/OpenVR-MotionCompensation#3]
If you have research or docs related to haptics interfering with tracking, please comment and add them.  When the time comes, we can review these resources to attempt to formulate a plan and potential solution.

**Comment by rosskevin** [comment]
https://community.viveport.com/t5/Developer-Discussion/Vive-Tracker-Airsoft-Gun-Recoil-floating-issues/m-p/12146/highlight/true#M154

Haptics disturb vive tracker

> This is a known issue with a verified solution. Forceful haptics create a disturbance that will cause the IMU to output erroneous data. A 3ms haptic pulse that couples into the IMU doesn’t create a 3ms acceleration disturbance.  It causes the IMU to output that erroneous data for 100-200ms.  If you attempt to ignore that data, it’s easy to chain together enough haptics that you are essentially ignoring the IMU forever. There is a method to filter the event that has been used successfully and it is outlined in the 1.5 Tracker Dev Guidelines that can be found that the link below. The Tracker FW build that supports this functionality is available now.
>
> Even with this solution, you should provide damping and secure the Tracker firmly to the peripheral to mechanically isolate the IMU from the vibration source.
>
>https://dl.vive.com/Tracker/Guideline/HTC_Vive_Tracker_Developer_Guidelines_v1.5.pdf

There are a few different attempts at isolation, but none that totally solved it for the gun with recoil.  My general thought is that an isolation platform plus implementation of the referenced filter may get us there.

**Comment by pottedmeat7** [comment]
If this is compensating motion for a vive tracker a possible solution would be to make a software defined "clone" of the device. 
This wouldn't work for the HMD because if you have two instances of the HMD you will still be looking through one. But as a tracker you could remove all references to haptics in your clone and just monitor the XYZ position/velocity of the parent, that may benefit the compensating algorithms.
This is something maybe to try...
Also i'm curious as to the exact use of the tracker, is it supposed to move at all or is it just a static reference point?

**Comment by rosskevin** [comment]
@pottedmeat7 join me on discord and I can explain some background https://discord.gg/r7krmSd

**Comment by AfromD** [comment]
Would it maybe be possible, for our purposes, to not use the IMU readings? Short term accuracy would be affected, but that is maybe just what we need? So just use lighthouse tracking and no accelerations since it is less responsive, but accurate over the longer term?

**Comment by Dschadu** [comment]
Transducer interference with tracker is an hardware issue. OVRMC since added two filters to reduce vibrations and there is also the option to use a virtual tracker.
